saldo_btc = 0.0
klik_sila = 0.0001
pasywny_dochod_co_2s = 0.0

ulepszenia = {
    "programista": {
        "nazwa": "Programista z Salezjan",
        "cena": 0.001,
        "poziom": 0,
        "korzysc": 0.0002,
        "typ": "pasywny",
    },
    "monster": {
        "nazwa": "Monster White",
        "cena": 0.005,
        "poziom": 0,
        "korzysc": 0.0005,
        "typ": "pasywny",
    },
    "gemini": {
        "nazwa": "Gemini Pro",
        "cena": 0.1,
        "poziom": 0,
        "korzysc": 0.002,
        "typ": "klik",
    },
    "general": {
        "nazwa": "Generał Es",
        "cena": 1,
        "poziom": 0,
        "korzysc": 0.01,
        "typ": "klik",
    },
}
################################################67 tekstow
teksty_programistyczne = [
    "Napisano pętle w JS",
    "Połączono bazę danych ze stroną",
    "Pobrano kod z Githuba",
    "Naprawiono błąd 'Undefined is not a function'",
    "Skopiowano rozwiązanie ze Stack Overflow",
    "Zainstalowano paczkę przez npm",
    "Komputer zawiesił się przy kompilacji",
    "Dodano kolorowy cień (box-shadow) do przycisku",
    "Uruchomiono ponownie serwer lokalny (localhost)",
    "Zgubiono średnik w linijce 42",
    "Zrobiono commita z opisem 'fix bugs'",
    "Podłączono zmienną sesyjną w PHP",
    "Przetłumaczono stronę na język angielski przez Google",
    "Zaktualizowano sterowniki karty graficznej",
    "Wyczyszczono pamięć podręczną przeglądarki (cache)",
    "Wymyślono nowe hasło do bazy danych",
    "Zrobiono przerwę na kolejnego Monstera",
    "Zmieniono kolor tła na ciemny motyw (Dark Mode)",
    "Skonfigurowano reguły Flexboxa w CSS",
    "Pomyślnie wdrożono projekt na serwer testowy",
    "Opierdalano się",
    "Przekopiowano kod z gemini",
    "Boje się dziewczyn",
    "Co się kurwa lampisz",
    "Walnąłbym monsterka",
    "Jebać tuska",
    "Nie rozumiem pytania",
    "Witam panów i proszę o zajęcie miejsca",
    "Lufa",
    "Wejście na ptoszek.pl",
    "Pobranie watykańczyka",
    "Zainstalowano Linux Kali do hackowania pentagonu",
    "Kodowanie w PelcScript",
    "Modyfikowanie artykułu na stronie salezjanie.edu.pl",
    "Pisanie egzaminu INF.03",
    "Pisanie egzaminu INF.04",
    "Spanie na lekcji programowania obiektowego",
    "Wkurwianie się bo xampp nie działa",
    "Odłączenie koledze RJ-45"
    "Kradnięcię pamięci RAM"
    "Tworzenie tysiąca partycji dla żartu",
    "Hejtowanie sportu",
    "Ustawienie na pulpit zdjęcia alternatywek",
    "Usuwanie historii przeglądania",
    "Uwufufu",
    "Rozwiązywanie quizów na zagraj.my",
    "Gra w openguessr",
    "Pobieranie Roblox",
    "Konfigurowanie PC pod Geforce Now",
    "Zmyślanie w CV",
    "Opierdalanie się w WordPressie",
    "Usuwanie ważnej bazy danych",
    "Kupowanie domeny",
    "Testowanie kompa przez TNT w minecraft",
    "Robienie benchmarku GPU",
    "Taktowanie CPU",
    "Ukrywanie ikon na pulpicie",
    "Usuwanie folderu pierwszakom",
    "Snusik pod ławką (nie ja) w sali 307 (rip 307)",
    "Tworzenie spotkania na teamsie",
    "Rozmontowywanie krzesła",
    "Rzucanie podłokietnikami",
    "Wkurwianie nauczycieli",
    "Wylanie dzika na klawiaturę",
    "Oglądanie walki meneli",
    "Oglądanie stopchamu",
    "Jechanie po windowsie",
    "Error 404",
]
